### ISSUE TITLE
UA deprecation / Client Hints

### ISSUE THREAD

**Issue by stwalkerster** [enwikipedia-acc/waca#817]
Related: https://github.com/UTRS2/utrs/issues/259

```[tasklist]
### Tasks
- [x] Database table for client hints
- [x] DataObject
- [x] Purge script update
- [x] Config to decide what to request / what to save
- [x] Actually request the information
- [x] Actually save the information
- [x] Display the information
- [x] Test on default form
- [x] Test on custom forms
- [x] Test purge script
```
